### PR TITLE
read_zarr() with credentials

### LINKED ISSUE #953: read_zarr() operation to accept credentials
### Expected behavior

Let `read_zarr()` operation also accept credentials when used with a S3 URL as `path`.

### Actual behavior

 `read_zarr()` forces anonymous object storage access.

### Specifications 

Cate 2.1.2

### PR DESCRIPTION
**Pull request by forman**
Closes #953

### CODE REVIEW

**Review by AliceBalfanz — CHANGES_REQUESTED** [review]
Works fine when using s3://some-bucket/some_cube.zarr in aws s3, however when using the url https://s3.eu-central-1.amazonaws.com/some-bucket/some_cube.zarr the cube is not read, shouldn't the second version be supported as well? 

When trying to access a cube stored in the otc cloud obs via 
https://obs.eu-de.otc.t-systems.com/some-bucket/some_cube.zarr this does not work at all. And when I pass s3://some-bucket/some_cube.zarr with file system OBS selected, there is not enough information about which cloud storage should be accessed. 
This should be changed

**Comment by forman** [comment]
You are right, thanks!

**Comment by forman** [comment]
Done.

**Review by AliceBalfanz — APPROVED** [review]
Works great! Thanks!

While testing, I noticed, that I cannot cancel the operation `read_zarr` like it is possible e.g. when opening a dataset from CCI. But this might be a separate issue and not part of this PR :)
image

**Pull request merged**
