### PR TITLE
Parse points from CSV

### LINKED ISSUE #935: Parse spatial points from CSV
# Expected behavior

If longitude and latitude columns are given in a CSV passed to the `read_csv()` operation, it should recognized and parsed into a new geometry columns. The result in this case should be a `geopandas.GeoDataFrame`.

This has been requested by users that participated in the first Cate App demo on 20.08.2020.

### Actual behavior

A  `pandas.DataFrame` is returned.

### Specifications 

Cate 2.1.0

### PR DESCRIPTION
**Pull request by forman**
Closes #935

**EDIT**

Verify:

Invoke `read_csv()` with a file with following content:

```
lat,lon,time,value,name
50.0,10.2,2020-02-08T11:40:53Z,234.3,Loc 1
52.5,11.2,2020-02-08T11:41:27Z,165.0,Loc 2
51.3,12.1,2020-02-08T11:42:12Z,198.4,Loc 3
53.9,10.8,2020-02-08T11:43:26Z,210.5,Loc 4
```

**EDIT**

Expected result:

image

(An issue remains, the Cesium viewer doesn't seem to re-render after feature loading.)

### CODE REVIEW

**Review by pont-us — APPROVED** [review]
Works for me!

**Review by dzelge — CHANGES_REQUESTED** [review]
Tests fail. There is a 500 error when testing. That's a bit odd
image

**Review by TonioF — APPROVED** [review]
Works (except for the re-rendering issue you mentioned).

**Comment by TonioF** [comment]
> Tests fail. There is a 500 error when testing. That's a bit odd
> image

That is not related to the PR.

**Pull request merged**
