### PR TITLE
changed all own error classes to use the Python 3 extended raise stat…

### PR DESCRIPTION
**Pull request by forman**
…ement: "raise my_error() from other_error"

### CODE REVIEW

**Comment by forman** [comment]
@kbernat, @mzuehlke, @JanisGailis 

Please review. This PR is about the Python 3 `raise` statement with `from` which we haven't used at all so far.

@kbernat please also have a look at `DataAccessError` class and its usages. which is much simpler now.

Last one to successfully review should merge please, thanks!

**Comment by JanisGailis** [comment]
Should we use a similar approach in ops?

**Comment by forman** [comment]
@JanisGailis you mean, introduce an `OperationError`? Only if we (must) handle this error type in specific way.

**Comment by JanisGailis** [comment]
OK, I didn't realize what the main reason for having own error classes was! No, I don't think we need an ``OperationError`` at the moment then.

**Pull request merged**
