### PR TITLE
340 jg lta fails

### LINKED ISSUE #340: Either temporal_aggregation or LTA fails
### Expected behavior

[Happy Path](https://github.com/CCI-Tools/cate-core/blob/master/scripts/uc06.sh) for UC06 should still work when one selects another period, but still uses the same dataset as in the happy path.

### Actual behavior

At some point from the temporal_aggregation to the LTA cate runs into an error.

### Steps to reproduce the problem

Please stick to the shell-script outlined [here](https://github.com/CCI-Tools/cate-e2e/blob/master/scripts/UC6/UC06_S2_v001.sh).

The LTA step returns:
"Long term average operation expects a monthly dataset running temporal aggregation on this dataset beforehand may help."
But within the script a temporal_aggregation step is calculated before.

### Specifications 

CLI, Linux, cate-0.9.0_dev5

### PR DESCRIPTION
**Pull request by JanisGailis**
* Use global temporal attributes to check temporal resolution in aggregation operations
* Adjust temporal attributes automatically upon reading a dataset
* Refactor 'normalize' operation implementation logic to util/opimpl
* Adjust temporal attributes automatically upon DatasetLike.convert
* Refactor 'subset' operation implementation logic to util/opimpl

Closes #340 
Goes a long way in solving #318

### CODE REVIEW

**Comment by JanisGailis** [comment]
Appveyor test fails although there's no difference between the feature branch and master in unit test code there. I'll go ahead and merge anyway.

**Comment by mzuehlke** [comment]
Hi @JanisGailis 

The failing tests in Appveyor are related to this PR. 😢 
in `adjust_temporal_attrs_impl` you create a copy of the ds: `ds = ds.copy()` before you alter some attributes. But then the close operation on the ds in the test does not work anymore because the copy does not propagate the `file_obj`, so the file is not closed and on Windows, the file can not be removed.

I have no good idea how to fix this....

**Comment by JanisGailis** [comment]
Cool, so the Unit test caught something :)

I'll also think about how to solve this.

**Comment by JanisGailis** [comment]
@mzuehlke I managed to fix the Appveyor build by implementing a context managed file handler that ignores the OSError when on Windows. I had used that approach in operation tests when I'm writing something to disk. The approach itself is largely borrowed from xarray people.

**Pull request merged**
