### PR TITLE
Make sure pearson_correlation_scalar input is validated

### PR DESCRIPTION
**Pull request by JanisGailis**
Input validation in pearson_correlation_scalar had faulty logic

### CODE REVIEW

**Comment by JanisGailis** [comment]
Closes #746 

The ``pearson_correlation_scalar`` is meant to work only on 1D variables (much like the underlying scipy function). I had a check for 3D variables, which was faulty. This PR resolves that, but the operation you were trying to carry out in #746 will then fail anyway, just with a nicer message.

**Comment by JanisGailis** [comment]
@forman Merge when ready. If this is not merged in a day, I'll go ahead and do it myself.

**Comment by forman** [comment]
@JanisGailis merging this, but please answer my question once you have time!

**Comment by JanisGailis** [comment]
@forman Using ``.values.flatten()`` on an ND ``xarray.DataArray``, is a bad idea, as it will very likely run into ``MemoryError`` in many instances.

However, after some quick investigations, ``xr.DataArray.stack()`` could be used to achieve what you suggest in a memory safe way. This probably means that the datasets will have to be coregistered beforehand, for the operation to make any sense on ND inputs. This shouldn't take too long to implement. Should I go ahead?

**Comment by forman** [comment]
I actually did not mean the numpy `flatten()`, but just *flatten*, turn ND into 1D. So, yes, fine!

**Pull request merged**
